webdriver {

  driver = chrome

  autodownload = true

  capabilities {

    browserName = "chrome"

    "goog:chromeOptions" {

      args = [
        "--start-maximized",
        "--disable-notifications",
        "--disable-infobars",
        "--remote-allow-origins=*"
      ]
    }
  }
}

serenity {

  project.name = "SauceDemo Automation"

  take.screenshots = FOR_FAILURES

  restart.browser.for.each = NEVER
}

webdriver.timeouts {

  implicitlywait = 5000
}

chrome.switches = "--remote-allow-origins=*"